pipeline {
  agent any
  environment {
     GOOGLE_APPLICATION_CREDENTIALS = credentials('gcp-sa')
  }
  stages {
     stage('Connecting to Git') {
        steps {
          git branch: 'feature/PHANI/', url: 'https://github.com/sgandeplli/devops-project.git'
        }
     }

     stage('Terraform Initialization') {
        steps {
          sh 'terraform init'
          sh 'terraform plan'
          sh 'terraform apply -auto-approve'
        }
     }
  }
}
